### ISSUE TITLE
No method matching next(::AutoGrad.Rec{Dict{Symbol,Any}}, ::Int64)

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#109]
I am trying to add L2 regularization at the end of` s2s()` method in `prof/s2s.jl` and get the mentioned error. The added line is

```julia
sumlogp += 0.001 * sum(sumabs2(a) for (k,a) in model if isa(a, KnetArray))
```

**Comment by denizyuret** [comment]
I will look into this.  In the meantime a workaround is to replace the
dictionary with an array.

**Comment by denizyuret** [comment]
I had a chance to look at this in more detail, there were several problems:
* AutoGrad does not support Dict iteration. This can be fixed by:
```
Base.next{T<:Associative}(a::Rec{T},i) = ((kv,j)=next(a.value,i);(k,v)=kv;(k=>a[k],j))
```
I will add this to AutoGrad.
* `isa(a, KnetArray)` won't work, you need `isa(getval(a),KnetArray)`. When you index elements of a model AutoGrad changes their type to keep track of dependencies.
* Finally this won't work either because the model has a hierarchical structure and not all values are KnetArrays.  If you really want to calculate L2, I'd write a function that explicitly goes through `model[:embed1]`, `model[:encode][1]`, `model[:encode][2]` etc.

**Comment by denizyuret** [comment]
Fixed in latest AutoGrad master.
