### ISSUE TITLE
Deconvolution

### ISSUE THREAD

**Issue by jgbos** [denizyuret/Knet.jl#135]
I'm looking to use `deconv4` and noticed it was not setup to handle different output channel size.  The way to fix it is in the function `dcdims` by replacing the line

```julia
...
  elseif i == N-1
            size(w,N)
...
```

with

```julia
...
  elseif i == N-1
            size(w,N-1)
...
```

The reason for this has to do with using the backward `conv4` functions for the forward pass.  This means the input and output dimensions are switched for weights though.  Unfortunately I don't know `cudnn` good enough to add `output_padding` like PyTorch does.  Looking into it and will provide a pull request once I figure it out.  I'm currently getting a cudnn error when I try to add it.

**Comment by denizyuret** [comment]
@ekyurdakul any suggestions?

**Comment by ilkerkesen** [comment]
Same issue with #232

**Comment by ekinakyurek** [comment]
I think we should close this since #232 is closed.

**Comment by denizyuret** [comment]
@ilkerkesen does your implementation fix this?

**Comment by ilkerkesen** [comment]
Yes, this is a duplicate issue and there should not be any problem right
now.

On Dec 24, 2017 7:03 PM, "denizyuret" <notifications@github.com> wrote:

@ilkerkesen <https://github.com/ilkerkesen> does your implementation fix
this?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/denizyuret/Knet.jl/issues/135#issuecomment-353791801>,
or mute the thread
