### ISSUE TITLE
Package test fails for some functions

### ISSUE THREAD

**Issue by ognkrmms** [denizyuret/Knet.jl#167]
Hi,
I have an Ubuntu machine with Geforce Titan Xp on it. I have julia 0.6 and Knet 0.8.4. Pkg.test("Knet") throws some errors but I can run example codes like resnet or charlm. I tried building Knet directly in src folder with make but that didn't help. Please find the whole error report in the attachment.
[knet_test_fail.txt](https://github.com/denizyuret/Knet.jl/files/1329885/knet_test_fail.txt)

**Comment by denizyuret** [comment]
These tests pass on a K80 machine with the following configuration, can you share your configuration:
```
julia> include(Pkg.dir("Knet/test/gpu.jl"))
(Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion, Knet.cudnnVersion) = (8000, 8000, 8000, 6021)
julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by ognkrmms** [comment]
julia> include(Pkg.dir("Knet/test/gpu.jl"))
(Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion, Knet.cudnnVersion) = (8000, 8000, 8000, 5110)

julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)

**Comment by denizyuret** [comment]
This looks like the compilation of libknet8 during build did not go through.  The errors are caused by not finding the functions minabs and maxabs in libknet8.  I would go to .julia/v0.6/Knet/src and do a make clean; make.  See if there are any error messages.  Then remove .julia/lib/v0.6/Knet.ji and try the test again. Finally if this doesn't fix it you may need the compiler option in the Makefile mentioned in https://github.com/denizyuret/Knet.jl/pull/154.
