### ISSUE TITLE
Ku dependency parser gets slower within time

### ISSUE THREAD

**Issue by kirnap** [denizyuret/Knet.jl#171]
Dependency parser gets slower within time, here is a procedure to replicate it:
1st clone the repo and checkout to the experiments branch
```
  git clone https://github.com/kirnap/ku-dependency-parser.git
  cd ku-dependency-parser/
  git checkout experiments
```
After that you can either run the experiment.sh script or manually write the code in experiments.sh

**Comment by denizyuret** [comment]
Using `cat` with 100s of arguments in `features.jl` is the culprit. Every call may have a different type signature because of the positions of `Rec` args. This causes extra compilation during runtime of first epoch. The new `cat1d` function I implemented in `AutoGrad.jl` is more efficient and avoids extra compilation.
