### ISSUE TITLE
"no compilers found, libknet8 will not be built" on Windows 10

### ISSUE THREAD

**Issue by Alexey2257** [denizyuret/Knet.jl#297]
While building Knet on windows 10 I got an error  "no compilers found, libknet8 will not be built." I have latest Knet, Julia 0.6.2.2, CUDA 9.1, cudnn and CMake 3.11.0 installed. Do i need to install something else? I checked similar issue #131 but didn't find answer there.

Pkg.test("Knet") gives an error: "Cannot find libknet8, please rerun Pkg.build("Knet")."

**Comment by DilumAluthge** [comment]
Which version of Visual Studio do you have installed? I believe that the latest version does not currently work (https://github.com/denizyuret/Knet.jl/blob/master/deps/README.windows).

**Comment by denizyuret** [comment]
I suggest trying the latest Knet master using Pkg.checkout("Knet"), which uses the CUDAapi package and retry.  If this succeeds please let me know the cuda, cudnn, and visual studio version you are using, so I can update the readme.  If this fails this could be because CUDAapi failed to discover the tools / libraries (in which case we should open an issue there), or Knet messed something up (in which case I will help debug and fix).
