### ISSUE TITLE
mnist.jl dies on missing Knet.dir 

### ISSUE THREAD

**Issue by noisebrain** [denizyuret/Knet.jl#34]
Using julia0.5 and the Knet obtained from the julia package system (i.e. Pkg.add("Knet")),
the mnist example dies with this error:

```
INFO: Loading MNIST...
ERROR: LoadError: UndefVarError: dir not defined
 in loaddata() at /Users/zilla/zilla/Devl/Julia/Knet/Mnist/mnist.jl:137
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/zilla/zilla/Devl/Julia/Knet/Mnist/mnist.jl, in expression starting on line 152
--------
julia> @doc Knet.dir
  No documentation found.

  Binding Knet.dir does not exist.
```

A version cloned from this repo (Knet.jl) works however.

**Comment by denizyuret** [comment]
The mnist example provided with the released version of Knet (0.8.0 which Pkg.add("Knet") installs) should work: see https://github.com/denizyuret/Knet.jl/blob/v0.8.0/examples/mnist.jl

The problem seems to be trying to run the example from the latest version of Knet (which has Knet.dir defined), with the released version of the code (which does not have Knet.dir defined).
