### ISSUE TITLE
KnetArray transpose and permutedims missing.

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#39]

**Comment by denizyuret** [comment]
Is permutedims for 4D and 5D practical?  Necessary?

**Comment by denizyuret** [comment]
I am leaving this issue open for the general N-D implementation.

**Comment by denizyuret** [comment]
@ilkerkesen do we actually have a general N-D implementation (beyond 5-D) that works?  If so, let's close this.

**Comment by ilkerkesen** [comment]
Back then I implemented a general permutedims operation, but couldn't port
it to Knet. Yes, we have, but it needs to be ported.

On Dec 24, 2017 6:55 PM, "denizyuret" <notifications@github.com> wrote:

@ilkerkesen <https://github.com/ilkerkesen> do we actually have a general
N-D implementation (beyond 5-D) that works? If so, let's close this.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/denizyuret/Knet.jl/issues/39#issuecomment-353791444>,
or mute the thread

**Comment by ilkerkesen** [comment]
Caffe2 has a [multi-dimensional transpose operation](https://caffe2.ai/docs/operators-catalogue#transpose) in the way we desire. It takes advantage of cudnn's `cudnnTransformTensor` kernel. I'm on it.

**Comment by denizyuret** [comment]
Solved using CuArrays under permutedims branch, please test.
