### ISSUE TITLE
Knet uses a lot of RAM in the using statement alone

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#58]
If I run ```julia -p 12``` and then ```using Knet``` my RAM usage blows up +6GB. If I run just ```julia``` and then ```using Knet``` it consumes ~500MB. So the amount of RAM consumed scales linearly with the number of worker processes. Is this a normal behaviour? I saw ```AutoGrad``` consumed just ~ 50 MB for 12 processes.

**Comment by denizyuret** [comment]
julia -p N creates N+1 independent julia processes.  On my machine each
julia process eats about 150 MB and Knet adds another 250 MB.  Almost all
of this seems to be due to GPU support: on a CPU only machine Knet adds
about 2MB per process.  If this poses a problem we need to fiddle with the
GPU initialization code to see where all this memory is going -- my guess
is the NVIDIA libraries.

deniz

**Comment by denizyuret** [comment]
Here is a table of memory costs (reported by ps and free) for reference.  The last two rows spawn 13 processes, so the total memory cost is 13x the provided numbers.  Roughly speaking, Knet adds 30 MB on top of Julia.  Initializing the cublas and cudnn handles adds 350 MB.

|operation|cpu-free|cpu-ps|gpu-free|gpu-ps|
|---------|---------|-------|---------|-------|
|julia|109580|154428|108060|164596|
|using Knet|129736|178572|448984|533692|
|julia -p12|157615|200840|153418|210640|
|using Knet -p12|162199|208792|439799|564336|
