### ISSUE TITLE
Knet GPU selection and auto device selection

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#586]
Moving to CUDA.jl, which of the following should I use to select a GPU?
```
Knet.gpu(GPU)
Knet.device!(GPU)
CUDA.device!(GPU)
```

**Comment by denizyuret** [comment]
`CUDA.device!(GPU)` should be preferred in the future. `Knet.gpu(GPU)=CUDA.device!(GPU)` is also defined for backward compatibility.

**Comment by denizyuret** [comment]
Info from Tim:

On 2020-07-25 21:32, Deniz Yuret wrote:
> 1. How is the initial device chosen in a multi-gpu machine? In
> particular do we look for one with most available memory?

Follows CUDA conventions, i.e. device 0. Just call `device!` and all
future new device requests (e.g. when initializing a new task) will use
that device. Logic at
https://github.com/JuliaGPU/CUDA.jl/blob/afaec8e0b2a89e09e65f8977c1312b8846c561ed/src/state.jl#L42-L60

> 2. What is the right way to restart working on a device after a
> device_reset!

Doing any API call should re-initialize it again. Note that device_reset
is particularly tricky, since the CUDA driver API doesn't have a
convenient API for it, so it might not be 100% stable. One known issue
is that if you allocate data and then reset, that data may stick around
in the memory pool and get reused later on, causing errors. That will be
fixed by https://github.com/JuliaGPU/CUDA.jl/pull/253, where those
allocations are bound to a context (which we can check for validity).

> 3. Is there a valid state with no active devices?

Yes, on a thread before doing any API calls or after a device reset
you'll see no CUDA context is active (e.g. by inspecting `nvidia-smi`
where you'll see no GPU memory bound to the process).

> 4. Can we go back and forth between two devices with device! and keep
> arrays on both?

Currently not, that's the limitation described above and in
https://juliagpu.gitlab.io/CUDA.jl/usage/multigpu/#Scenario-2:-Multiple-GPUs-per-process-1.
However, the PR linked above also should fix that, so we'll have that
ability soon enough (although it'll still be your responsibility to
switch devices before using data on it).

If you have suggestions about how this should work based on Knet/CUDArt
experience, feel free to suggest those. Nothing is set in stone yet
(multi-device/thread/task capabilities are recent, with few users).
