### ISSUE TITLE
About overwriting arrays

### ISSUE THREAD

**Issue by mambuDL** [denizyuret/Knet.jl#83]
Hi, 
I believe KNET is  one of the most easy to use deep learning frameworks. Thanks for such a product! If you don't mind I have some questions about it. In tutorial.md, under philosophy section, you are saying "Knet builds a dynamic computational graph by recording primitive operations during forward calculation."  From that warning I understand, I cannot overwrite anything inside the loss function. However, when I look at predict function of `examples/charlm.jl` file . I see you're overwriting state values (`line 222`). So, isn't it contradiction?  Could  you give some examples to show me some valid and forbidden cases inside loss function? 

I added a couple of lines into your official example just to understand in which cases overwriting  is forbidden. (I know it is not a meaningful thing but I couldn't find any good example)

```
function predict(w, s, x)
    x = x * w[end-2]
    arr = Any[]
    for i = 1:2:length(s)
        (s[i],s[i+1]) = lstm(w[i],w[i+1],s[i],s[i+1],x)
        x = s[i]
        push!(arr,s[i]) # I add this line to your official example 
    end
    return x * w[end-1] .+ w[end],arr
end

function loss(param,state,sequence,range=1:length(sequence)-1)
    total = 0.0; count = 0
    atype = typeof(AutoGrad.getval(param[1]))
    input = convert(atype,sequence[first(range)])
    
     for t in range
        ypred,states = predict(param,state,input)
        ynorm = logp(ypred,2) # ypred .- log(sum(exp(ypred),2))
        ygold = convert(atype,sequence[t+1])
        total += sum(ygold .* ynorm)
        count += size(ygold,1)
        input = ygold
        s = states[1]                      # extra steps start here 
        for ss in states[2:end]
          s = hcat(s,ss)                      # I believe its kind of overwriting too 
       end 
    end
    return (-total + sum(s)) / count
end

```
Above, I wonder are the extra lines added by me valid or not ?  Again it would be very informative to have some valid/invalid examples to get the idea clearly.

**Comment by ozanarkancan** [comment]
```julia
h = zeros(100, 1)
for x in data
h = f(w, h, x)#simple rnn
end
```

In the above code snippet, when you assign new values to h, a new node is created for new h on the computation tape. The basic rule is not to use a method with ! in the forward computation.

```julia
push!(arr,s[i]) # not ok
s = states[1] 
for ss in states[2:end]
    s = hcat(s,ss)# this is ok, since you create new s at each time step, you don't override it
end
```

**Comment by mambuDL** [comment]
I'm surprised because I thought storing matrices, generated during forward calculation like s matrices above, wouldn't be a problem. Then, I assume  this overwriting problem is not only about weights of model right ?  Also, I guess there is no way to store such values to use them later during forward pass unfortunately. I believe I would feel more secure myself if I get an error message  while attempting such illegal  operations during forward/backward passes. (Currently I don't get any error while populating s arrays inside arr)

**Comment by denizyuret** [comment]
Hi Jaymes,

You should get an error.

AutoGrad works by boxing the argument wrt which you are taking the
gradient. Then every result whose value depends on this argument also gets
boxed and its operation recorded with pointers to inputs and outputs.
Operations like setindex!, push! and copy! are purposely not defined for
such boxed values and should lead to an error.

If you don't get an error, either the value is not boxed or it is a bug.
The first may happen if the value does not lie on a computational path from
the original boxed arg to loss. If that is not the case, then gradcheck
should fail and we should worry.

best,
deniz

**Comment by mambuDL** [comment]
Hi, 
Thank you for your reply. To see which of these two options are valid for my case, I made a 3 lines modification to your charlm.jl code. You can find it here: https://gist.github.com/mambuDL/062fe42a2615ad5788b3e001a02928ff

I add results at the end of file. Apparently,  loss values change even though not in a good way. I guess it means sum of states affects the final result and therefore we can say that it is on the computation graph, right? On the other hand, the code run without giving any error. So I think it is a bug huh?

**Comment by denizyuret** [comment]
Here is a much simpler example that gives the wrong gradient:
```julia
function f(x,r)      # x is boxed, r is not when taking gradient wrt arg1                                                                               
    y = x .* r       # y is boxed, operation x.*r recorded                                                                 
    #scale!(y,2)     # would give an error for boxed y                                                                     
    scale!(r,2)      # gives no error but ruins recorded operation                                                                   
    return sum(y)
end
```
The "protection" of having `scale!` etc. undefined for boxed values only warn the user when they apply these operations to a boxed value, i.e. the target argument or anything derived from it.  All other values, i.e. other arguments and values constructed within the function, are not boxed, so they don't get warnings.  Here are some bad solutions:
* copy every value we record instead of using pointers, which would create an unacceptable performance cost.
* box all arguments (which is feasible) and modify any array creation operations within the function (which is not).

In the short term I don't see an easy solution but I am open to suggestions.  In the long term I was thinking of rearchitecting AutoGrad to support overwriting, but the functional programming style is growing on me and is not as inefficient as I thought. Some overwriting operations are safe, but I don't see an easy way of demarcating them either. For now I think it would be easiest to say don't use any bang (!) operations in functions you want to take gradients, and change the charlm example to be compatible.

**Comment by mambuDL** [comment]
Thank you for your patient and answer. From your simple exercise, I got many important facts about KNET.  I believe this issue will be a good source for absolute KNET beginners. Therefore, I just want to clarify a couple of more points.

1) In your example, `scale!(r,2)` shouldn’t be done because, it changes the value of r which is used in boxed operation `y=x.*r` . I’m okay up to this point. But in my point of view, Inside charlm.jl, in [line 222](https://github.com/denizyuret/Knet.jl/blob/master/examples/charlm.jl#L222), you manipulate state and cell values at each time step `(s[i],[si+1]) = lstm(….) `, and then the hidden value (`s[1]`) is used in a boxed operation (`x * w[end-1] .+ w[end]`) where x is the s[1] at line [225](https://github.com/denizyuret/Knet.jl/blob/master/examples/charlm.jl#L225). I still have difficulty in understanding the difference between the operation` y= x.* r `and` scale!(r,2)` in your example and the lines 222 and 225 in charlm.jl. Could you make the distinction between these two pattern more clear?

2) For my second point, let's go over a  toy scenario. Assume, we have a language model like charlm. I unroll the model t times (t is set to 100 in your example), I need to find a way to store each of these 100 hidden state values. At t = 100, I want to take the weighted sum of these 100 hidden states and add this weighted sum to final hidden state of the model. Do you know how could I achieve it in a safe way ? I thought I could do it by storing each of these hidden states inside an array and using them at the last time step. (assume I use `push!(arr, s[1]) `just after [line 222](https://github.com/denizyuret/Knet.jl/blob/master/examples/charlm.jl#L222)). But now, I decide from your answers it is not safe. Although the scenario I explained might seem weird,  similar steps would be necessary during implementation of many popular deep learning models that uses its middle results during following steps in forward propagation. 

Again, I want to  thank you for your patient and fast and well documented explanations.

**Comment by ilkerkesen** [comment]
For your second question take a look at [my bidirectional lstm example](https://github.com/ilkerkesen/dynet-benchmark/blob/knet/knet/bilstm-tagger.jl#L258). In this example, I need to store all hidden state values, so I've used two state history arrays for forward and backward RNNs. By the way, I've tried it with your approach (initialize an empty array, then fill the array by using push! function), it gives the same gradients. In addition, you do not need to store these hidden states for your example, accumulate the sum by just adding the current hidden state to the previous states' sum (like that `states_sum = states_sum + this_state`).

**Comment by mambuDL** [comment]
Thank for your information. Then from your example I conclude that there is no problem with using `push! `method. (Although in the previous two comments it is said that push! is also dangerous to use). I'd be very happy if I get an explanation for my first question.

**Comment by denizyuret** [comment]
Sorry for the late response.  

The short answer to whether a particular operation is safe is `gradcheck`.  If your loss function passes `gradcheck` then you have not performed any bad overwrites.

The detailed answer to your first question is as follows: In case of the `scale!(r,2)` example you are overwriting a numerical array that was an input to a recorded operation rendering the record invalid. When charlm overwrites `s` this does not hurt anything because the `s` array itself is not boxed and does not take part in any recorded operation, only its elements `s[i]` do.  When you have a statement like `x += s[i]` for example, the primitive `+` operation only uses and records the pointers to `x` and `s[i]`, but not one to `s`. So modifying the `s` array (e.g. by changing one of its elements) is ok because `s` is not recorded anywhere, but modifying one of the `s[i]` elements (e.g. by `scale!`) would be bad if they have intermingled with boxed values and got recorded.

Generally the low level numerical arrays are dangerous to modify, but modifying containers (arrays of arrays, dictionaries etc.) are typically ok (the one exception is the w parameter you are taking gradient with respect to).

I think it is unfair to expect Knet beginners (or experts for that matter) to keep track of all this, so I suggest not to use overwriting (a better charlm example is in my todo list), and if you must overwrite, use `gradcheck` to make sure nothing necessary got corrupted.

**Comment by mambuDL** [comment]
Thank you for such a well-prepared answer! Now I have quite better understanding about Knet.
