### ISSUE TITLE
Array order

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#98]
I saw that there are two ways of input-param array ordering in the examples:
The first:
```
output = input * param[1] .+ param[2]
```
The second:
```
output = param[1] * input .+ param[2]
```
Is there any preference or performance gain when choosing one instead of the other?

**Comment by denizyuret** [comment]
Both variants compute the same thing.

One case for preferring one to the other are models where you want to
perform concatenation or slicing.  Julia is column major, so horizontal
concatenation and column based slicing are contiguous and more efficient
compared to vertical concatenation and row slicing. In LSTM models you may
want to perform one matrix multiplication for all four gates rather than
four (or eight) separate matrix multiplications. Thus in the charlm example
LSTM concatenates the input and the hidden, then slices the output gates.
Both operations are more efficient if instances are in rows rather than
columns.

deniz

**Comment by ngphuoc** [comment]
Thanks a lot for your helpful explanation!
